CREATE TABLE IF NOT EXISTS students (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    student_number VARCHAR(30) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    course VARCHAR(100) NOT NULL,
    year_level INT NOT NULL,
    email VARCHAR(120) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_students_student_number UNIQUE (student_number)
    );

CREATE TABLE IF NOT EXISTS users (
                                     id INT GENERATED BY DEFAULT AS IDENTITY,
                                     username VARCHAR(50) NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
    );

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_students_updated_at ON students;

CREATE TRIGGER trg_students_updated_at
    BEFORE UPDATE ON students
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

INSERT INTO students (
    student_number,
    first_name,
    last_name,
    course,
    year_level,
    email,
    phone
) VALUES
      ('2024-0001', 'Steffanie', 'Yola', 'BSIT', 2, 'steffanie.yola@example.com', '09170000001'),
      ('2024-0002', 'Tobio', 'Kageyama', 'BSIT', 2, 'tobio.kageyama@example.com', '09170000002'),
      ('2024-0003', 'Arianne', 'Alcabasa', 'BSIT', 2, 'arianne.alcabasa@example.com', '09170000003'),
      ('2024-0004', 'Erica', 'Fernandez', 'BSIT', 2, 'erica.fernandez@example.com', '09170000004'),
      ('2024-0005', 'John', 'Sasi', 'BSIT', 2, 'john.sasi@example.com', '09170000005'),
      ('2024-0006', 'Vinz', 'Tejero', 'ECE', 2, 'vinz.tejero@example.com', '09170000006'),
      ('2024-0007', 'Shoyo', 'Hinata', 'ECE', 3, 'shoyo.hinata@example.com', '09170000007'),
      ('2024-0008', 'Kei', 'Tsukishima', 'ECE', 4, 'kei.tsukishima@example.com', '09170000008'),
      ('2024-0009', 'Keith', 'Espejo', 'ECE', 3, 'keith.espejo@example.com', '09170000009'),
      ('2024-0010', 'Cholo', 'Perez', 'ECE', 1, 'cholo.perez@example.com', '09170000010'),
      ('2024-0011', 'Aizel', 'Caruyan', 'ECE', 1, 'aizel.caruyan@example.com', '09170000011'),
      ('2024-0012', 'Daichi', 'Sawamura', 'BSED', 2, 'daichi.sawamura@example.com', '09170000012'),
      ('2024-0013', 'Tetsuro', 'Kuroo', 'BSED', 3, 'tetsuro.kuroo@example.com', '09170000013'),
      ('2024-0014', 'Frieren', 'The Slayer', 'BSA', 4, 'frieren.slayer@example.com', '09170000014'),
      ('2024-0015', 'Himmel', 'The Hero', 'BSA', 3, 'himmel.hero@example.com', '09170000015');

INSERT INTO users (username, password_hash) VALUES
                                                ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'),
                                                ('student', '703b0a3d6ad75b649a28adde7d83c6251da457549263bc7ff45ec709b0a8448b');